syntax = "proto3";

package product;

// Representasi dari kumpulan data produk afiliasi
message ProductList {
  repeated Product products = 1;
}

// Representasi dari satu baris data produk afiliasi
message Product {
  int64 id_produk = 1;                 // ID unik produk (contoh: 21774343983)
  string nama_produk = 2;             // Nama produk
  string harga = 3;                   // Harga dalam bentuk teks display (contoh: "269,0RB")
  int32 penjualan = 4;                // Jumlah penjualan numerik (contoh: 410)
  string nama_toko = 5;               // Nama toko penjual
  string komisi_hingga = 6;           // Persentase komisi maksimal (contoh: "10%")
  string komisi = 7;                  // Nominal komisi dalam teks (contoh: "Rp26.900")
  string link_produk = 8;             // URL asli menuju produk Shopee
  string link_komisi_ekstra = 9;      // URL pelacakan komisi ekstra (s.shopee.co.id)
}